changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - breaking-changes
    - title: New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Bug Fixes 🛠
      labels:
        - bug
    - title: Performance Improvements ⚡
      labels:
        - performance
    - title: Documentation 📝
      labels:
        - documentation
    - title: Other Changes 🔧
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - enhancement
          - feature
          - bug
          - fix
          - performance
          - documentation
          - breaking-changes
    - title: Dependencies 👒
      labels:
        - dependencies
