// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Emmet
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GuidEmmetPackageString = "28e5fe40-f8d1-4720-8fdb-42a638b75fe5";
        public const string GuidEmmetPackageCmdSetString = "8e070628-bb22-4983-99e8-ac37608cc5a6";
        public const string GuidVisualStudioHtmlEditorCmdSetString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public const string GuidVisualStudioCssEditorCmdSetString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid GuidEmmetPackage = new Guid(GuidEmmetPackageString);
        public static Guid GuidEmmetPackageCmdSet = new Guid(GuidEmmetPackageCmdSetString);
        public static Guid GuidVisualStudioHtmlEditorCmdSet = new Guid(GuidVisualStudioHtmlEditorCmdSetString);
        public static Guid GuidVisualStudioCssEditorCmdSet = new Guid(GuidVisualStudioCssEditorCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDCssEditorContextMenuGroup = 0x1020;
        public const int IDHtmlEditorContextMenuGroup = 0x1021;
        public const int IDEmmetCssCmdGroup = 0x1030;
        public const int IDEmmetHtmlCmdGroup = 0x1031;
        public const int IDEmmetCSharpCmdGroup = 0x1032;
        public const int IDEmmetCssContextMenu = 0x1040;
        public const int IDEmmetHtmlContextMenu = 0x1041;
        public const int CmdIDExpandAbbreviation = 0x0100;
        public const int CmdIDWrapWithAbbreviation = 0x0101;
        public const int CmdIDToggleComment = 0x0102;
        public const int CmdIDMergeLines = 0x0103;
        public const int CmdIDExpandMnemonic = 0x0104;
        public const int IDVisualStudioHtmlContextMenu = 0x0001;
        public const int IDVisualStudioCssContextMenu = 0x0002;
    }
}
