// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.175
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Emmet
{
    static class Vsix
    {
        public const string Id = "Emmet.net.Sergey Rybalkin.9a011f0e-c870-4faa-aaee-536a8040385c";
        public const string Name = "Emmet.net";
        public const string Description = "Visual Studio port of the https://github.com/emmetio/emmet project by Sergey Chikuyonok.";
        public const string Language = "en-US";
        public const string Version = "3.1.1";
        public const string Author = "Sergey Rybalkin";
        public const string Tags = "Emmet";
    }
}
