//------------------------------------------------------------------------------
// <auto-generated>
// Data access layer code generator.
// </auto-generated>
//------------------------------------------------------------------------------
using System.CodeDom.Compiler;

namespace Emmet.Tests.Helpers
{
    [GeneratedCode("TestHelperGenerator", "1.0")]
    public static partial class DataHelper
    {
        public const string Abbreviation = "Abbreviation.html";
        public const string AbbreviationGold = "AbbreviationGold.html";
        public const string AbbreviationInJsx = "AbbreviationInJsx.jsx";
        public const string AbbreviationInJsxGold = "AbbreviationInJsxGold.jsx";
        public const string MergeLines = "MergeLines.html";
        public const string MergeLinesGold = "MergeLinesGold.html";
        public const string preferences = "preferences.json";
        public const string ToggleComment = "ToggleComment.html";
        public const string ToggleCommentGold = "ToggleCommentGold.html";
        public const string WrapWithAbbreviation = "WrapWithAbbreviation.html";
        public const string WrapWithAbbreviationGold = "WrapWithAbbreviationGold.html";
    }
}