<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <MinimumVisualStudioVersion>17.0</MinimumVisualStudioVersion>
    <TargetFramework>net472</TargetFramework>
    <AssemblyTitle>Emmet</AssemblyTitle>
    <Description>Visual Studio port of the https://github.com/emmetio/emmet coding assistant by Sergey Chikuyonok.</Description>
    <Company>Sergey Rybalkin</Company>
    <Product>Emmet</Product>
    <AssemblyVersion>6.0.1</AssemblyVersion>
    <FileVersion>6.0.1</FileVersion>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <VsixDeployOnDebug>true</VsixDeployOnDebug>
    <IncludeDebugSymbolsInLocalVSIXDeployment>true</IncludeDebugSymbolsInLocalVSIXDeployment>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="EmmetPackage.Constants.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmmetPackage.vsct</DependentUpon>
    </Compile>
    <Compile Update="Engine\Prompt.xaml.cs">
      <DependentUpon>Prompt.xaml</DependentUpon>
    </Compile>
    <Compile Update="Options.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="source.extension.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>source.extension.vsixmanifest</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
      <Generator>VsixManifestGenerator</Generator>
      <LastGenOutput>source.extension.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <CodeAnalysisDictionary Include="..\..\build\CodeAnalysisDictionary.xml">
      <Link>CodeAnalysisDictionary.xml</Link>
    </CodeAnalysisDictionary>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Data" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Design" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.V8" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VSSDK.BuildTools">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\emmet.js">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\emmet.min.js">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="source.extension.ico">
      <DependentUpon>source.extension.vsixmanifest</DependentUpon>
    </Content>
    <VSCTCompile Include="EmmetPackage.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
      <SubType>Designer</SubType>
      <Generator>VsctGenerator</Generator>
      <LastGenOutput>EmmetPackage.Constants.cs</LastGenOutput>
    </VSCTCompile>
    <Content Include="license.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\Logo.png">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\preferences.json">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Resources\PreviewImage.png">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\build\stylecop.json">
      <Link>stylecop.json</Link>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
    <Page Include="Engine\Prompt.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>
