// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Emmet
{
    internal sealed partial class Vsix
    {
        public const string Id = "Emmet.492f3c3b-cafd-4184-bb63-b3ba56bbe5cf";
        public const string Name = "Emmet";
        public const string Description = @"Visual Studio port of the https://github.com/emmetio/emmet coding assistant by Sergey Chikuyonok.";
        public const string Language = "en-US";
        public const string Version = "6.0.1";
        public const string Author = "Sergey Rybalkin";
        public const string Tags = "Emmet";
        public const bool IsPreview = false;
    }
}
